### ISSUE TITLE
Only work with credits?

### ISSUE THREAD

**Issue by nokai** [ebess/Fifa-14-Ultimate-Team-Mobile-WebApp-Api#1]
Only work with credits?

Does not work with search of players

**Comment by ebess** [comment]
Hi,
I have not looked for the search request in the mobile API but for sure you can login through the mobile endpoint and use export data for a common WebApp search request. You will have to append your nucleusId, phishingToken and sessionId as known.

Tell me if it doesn't help you and I will add a search request to the example.

PS:
I've commited example search request. You will have to update the fut/request-forge package. Just fixed a small bug. Please tell me if it worked out for you! ;)

**Comment by nokai** [comment]
Nothing, I've already got. thanks 
Use other different methods

Everything else has worked. 
Delete 'x-wap-profile and  change the user-agent of iphone

**Comment by rafaelget** [comment]
Hi, 

I'm still having issues to do searches.

Your examples gives me this:

Fatal error: Call to undefined method Guzzle\Http\Message\Request::setPostField() in /vendor/fut/request-forge/src/Fut/Request/Forge.php on line 429

What is the correct guzzle version? This one is auto installed with composer ( require {
        "fut/connectors": "dev-master"
    } )

Thanks

**Comment by ebess** [comment]
hey mate,

there was small bug which i have removed. take the v1.0.1 which should work out and update your composer packages:

"fut/connectors": "v1.0.1"
composer update

tell me if you stil have troubles

**Comment by rafaelget** [comment]
There is a problem with this version:

---

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for fut/connectors v1.0.1 -> satisfiable by fut/connectors[v1.0.1].
    - fut/connectors v1.0.1 requires fut/eahashor dev-master -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by rafaelget** [comment]
Fixed instalation with this on composer.json, but still having problems.
{
    "minimum-stability": "DEV",
    "require": {
        "fut/connectors": "1.0.1"
    }
}

---

Problem:

Fatal error: Call to undefined method Guzzle\Http\Message\Request::setPostField() in /vendor/fut/request-forge/src/Fut/Request/Forge.php on line 429

**Comment by ebess** [comment]
try to delete your vendor folder and your composer.lock. sometimes composer does not recognize that there are new package updates oO
