### ISSUE TITLE
new thing

### ISSUE THREAD

**Issue by meezohd** [ebess/Fifa-14-Ultimate-Team-Mobile-WebApp-Api#3]
hi 
thanks for this 

is there a sample code only to get players data ?

thanks

**Comment by ebess** [comment]
What do you mean by players data? The actual rating and all the IF cards?
If so, there is no way - at laest known to me - to fetch this data. You need to collect it yourself, I've a DB with all this data maintained by myself.

**Comment by meezohd** [comment]
I thought there is a way ... 
I also have all leagues, clubs, nations and players pictures... and old data of players but I was hopping for the new data.
will you upload the data someday ?

Date: Sun, 13 Jul 2014 03:59:21 -0700

**Comment by ebess** [comment]
Well, I could do that for Fifa 15. There is no real point in doing it for Fifa 14. Just hit me when the new Fifa is out.
