### ISSUE TITLE
PHP Fatal error:  Call to a member function setField()

### ISSUE THREAD

**Issue by Snoop** [ebess/Fifa-14-Ultimate-Team-Mobile-WebApp-Api#4]
Hi there, first thank you for this nice repo, there seems to be something wrong, just tested the example.php:

you have 500 coins
PHP Fatal error:  Call to a member function setField() on a non-object in /var/lib/openshift/53ea90024382ec30xxxxxx/app-root/runtime/repo/Fifa-14-Ultimate-Team-Mobile-WebApp-Api/vendor/fut/request-forge/src/Fut/Request/Forge.php on line 511

**Comment by ebess** [comment]
Hi mate,

do you pass a guzzle 4.1.\* client to the connector?
did you just pick the example from the example.php?
or are you using the 1.0.\* version of the package?

best regards
