### ISSUE TITLE
They've changed the logins/URL to the mobile app.

### ISSUE THREAD

**Issue by KmanProdz** [ebess/Fifa-14-Ultimate-Team-Mobile-WebApp-Api#5]
Any chance you will update? I found out some urls
"https://accounts.ea.com/connect/auth?client_id=FIFA-MOBILE-COMPANION&response_type=code&display=mobile/login&scope=basic.identity+offline+signin&locale=en&prompt=login";
"https://utas.mob.v4.fut.ea.com/ut/shards";
https://utas.s2.fut.ea.com/ut/game/fifa14/phishing/question?_=

Any chance you could get the validate link etc?

**Comment by ebess** [comment]
Hi, sorry mate, I was absent. I don't want to support the fifa 14 api anymore but i will take a look at it when I'll get to it upcoming days.

**Comment by KmanProdz** [comment]
Ohh, well the web app is reopened so I am using web app to login with client version 9 :)

**Comment by arthurnn** [comment]
I wonder if they will keep the same urls for login on fifa 15, do you know if they changed btw 13->14?

**Comment by filipholmberg** [comment]
Hi guys! if I understand this correct, do EA have an open API for developers/fans to get players data? if that is the case, its awesome. Can I read about this in more details anywhere?

**Comment by KmanProdz** [comment]
No, there is no official API and all API's you see on github is unofficial. Infact, making apps etc that require you to connect to EA servers with an API is unauthorized however, it's not breaking the game and is a good will. It's not too bad xD for Player stats @Curt2008 has made an Player API with all stats etc xD

**Comment by ebess** [comment]
hey guys, this repo is deprecated, just use the following:
https://github.com/ebess/Fifa-15-Ultimate-Team-WebApp-Api

packagist package name will stil the same, so if you update your project, it will take the fifa 15 endpoint to login.
